backend:
  name: git-gateway
  repo: FFXIVPocketGuide/FFXIVPocketGuide
  branch: rebuild

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'static/assets/guides/images'

mechanic-fields: &mechanic-fields
  label: 'Instance-wide Mechanics'
  name: 'instance-mechanics'
  widget: 'list'
  fields:
    - label: 'Mechanic Name'
      name: 'name'
      widget: 'string'
    - label: 'Mechanic Steps'
      name: 'steps'
      widget: 'list'
      fields:
        - label: 'Step Name or Number'
          name: 'name'
          widget: 'string'
        - label: 'Step Notes'
          name: 'notes'
          widget: 'list'
          field:
            label: 'Step Note'
            name: ''
            widget: 'string'

attack-name: &attack-name
  label: 'Attack Name'
  name: 'name'
  widget: 'string'

attack-duty-action: &attack-duty-action
  label: 'Duty Action'
  name: 'duty-action'
  widget: 'list'
  field:
    label: 'Duty Action Name'
    name: ''
    widget: 'string'

attack-roles: &attack-roles
  label: 'Required Party Roles'
  name: 'roles'
  widget: 'select'
  multiple: true
  options:
    - 'Everyone'
    - 'Tank'
    - 'Healer'
    - 'Melee DPS'
    - 'Ranged DPS'

attack-tags: &attack-tags
  label: 'Attack Types'
  name: 'tags'
  widget: 'select'
  multiple: true
  options:
    - Active Time Maneuver
    - Animation
    - AoE (Area)
    - AoE (Cone)
    - AoE (Circle)
    - AoE (Column)
    - AoE (Cross)
    - AoE (Donut)
    - AoE (Figure 8)
    - AoE (Point-blank)
    - AoE (Proximity)
    - Buff
    - Cleave
    - Debuff
    - Divebomb
    - Gaze
    - Knockback
    - Line-of-sight
    - Marker (Blue)
    - Marker (Green)
    - Marker (Icon)
    - Marker (Orange)
    - Marker (Purple)
    - Marker (Red)
    - Marker (Yellow)
    - Minion
    - Pull
    - Puddle
    - Raid-wide Damage
    - Spread
    - Stack
    - Stun
    - Tankbuster
    - Tether
    - Ultimate
    - Unique Mechanic

attack-notes: &attack-notes
  label: 'Attack Notes'
  name: 'notes'
  widget: 'list'
  field:
    label: 'Details'
    name: ''
    widget: 'string'

attack-images: &attack-images
  label: 'Attack Images'
  name: 'images'
  widget: 'list'
  hint: 'Useful for highlighting particular choreography on the arena or specific iconographies or telegraphs.'
  fields:
    - label: 'Image Upload'
      name: 'image'
      widget: 'image'
    - label: 'Image Alt Text'
      name: 'alt'
      widget: 'string'
      hint: 'Used to describe the image to assistive technologies.'

boss-fields: &boss-fields
  label: 'Bosses'
  name: 'bosses'
  widget: 'list'
  fields:
    - label: 'Boss Name'
      name: 'name'
      widget: 'string'
      required: true
    - label: 'Fight Phases'
      name: 'phases'
      summary: 'Boss Phase'
      widget: 'list'
      fields:
        - label: 'Phase Notes'
          name: 'notes'
          widget: 'list'
          field:
            label: 'Phase Note'
            name: ''
            widget: 'string'
        - label: 'Attack Script'
          name: 'script'
          widget: 'list'
          hint: 'An optional list of attacks showing their order during the fight. This is particularly useful for choreographed fights.'
          fields:
            - label: 'Attack Name'
              name: 'attack'
              widget: 'string'
            - label: 'Is a duty action required for this attack?'
              name: 'duty-action'
              widget: 'boolean'
              required: false
        - label: 'Boss Attacks'
          name: 'attacks'
          widget: 'list'
          types:
            - label: 'Regular Attack'
              name: 'Regular'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - *attack-name
                - *attack-duty-action
                - *attack-roles
                - *attack-tags
                - *attack-notes
                - *attack-images
            - label: 'Combo Attack'
              name: 'Combo'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - label: 'Combo Name'
                  name: 'name'
                  widget: 'string'
                - label: 'Attacks in the Combo'
                  name: 'combos'
                  widget: 'list'
                  fields:
                    - *attack-name
                    - *attack-duty-action
                    - *attack-roles
                    - *attack-tags
                    - *attack-notes
                    - *attack-images
            - label: 'Attack with Variations'
              name: 'Variation'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - label: 'Attack Name'
                  name: 'name'
                  widget: 'string'
                - label: 'Variations of the Attack'
                  name: 'variations'
                  widget: 'list'
                  fields:
                    - *attack-name
                    - *attack-duty-action
                    - *attack-roles
                    - *attack-tags
                    - *attack-notes
                    - *attack-images

guide-fields: &guide-fields
  - label: 'Guide Layout'
    name: 'layout'
    widget: 'hidden'
    required: true
    default: 'new-guide'
  - label: 'Content Management System'
    name: 'cms'
    widget: 'hidden'
    required: true
    default: 'netlify-cms'
  - label: 'Type of Instance'
    name: 'guide-type'
    widget: 'select'
    options:
      - 'Dungeon'
      - 'Trial'
      - 'Raid'
    required: true
  - label: 'Instance Title'
    name: 'title'
    widget: 'string'
    required: true
  - label: 'Page URL'
    name: 'slug'
    widget: 'string'
    required: true
    hint: "Used as the page's identifier in the resulting URL. We suggest simply a lowercase version of the Instance Title, with spaces replaced by dashes. e.g. Akadaemia Anyder > akadaemia-anyder"
  - label: 'Expansion'
    name: 'categories'
    widget: 'select'
    options:
      - label: 'Endwalker'
        value: 'ew'
      - label: 'Shadowbringers'
        value: 'shb'
      - label: 'Stormblood'
        value: 'sb'
      - label: 'Heavensward'
        value: 'hw'
      - label: 'A Realm Reborn'
        value: 'arr'
    required: true
  - label: 'Patch'
    name: 'patch'
    widget: 'number'
    value_type: 'float'
    required: true
  - label: 'Difficulty'
    name: 'difficulty'
    widget: 'select'
    options:
      - 'Normal'
      - 'Hard'
      - 'Extreme'
      - 'Savage'
      - 'Ultimate'
      - 'Unreal'
    required: true
  - label: 'Minimum Player Level'
    name: 'player-level'
    widget: 'number'
    value_type: 'int'
    required: true
  - label: 'Minimum Item Level'
    name: 'item-level'
    widget: 'number'
    value_type: 'int'
    required: true
  - label: 'Guide Order'
    name: 'order'
    widget: 'number'
    value_type: 'int'
    hint: 'This number determines where in the expansion the guide will fall on the homepage. Please combine the player level and item level together for best results. (e.g. 80 + 255 = 80255 )'
  - label: 'Page Description'
    name: 'description'
    widget: 'string'
    default: "Read our guide for the FFXIV [dungeon, trial, raid] [instance name] ([difficulty]), where you'll face off against [boss 1], [boss 2], and [boss 3]."
    required: true
  - label: 'Main Banner Image'
    name: 'hero-image'
    widget: 'image'
    hint: "1500px by 300px. This image will be displayed in the guide's header background."
    allowMultiple: false
    required: false
  - label: 'Thumbnail Image'
    name: 'list-image'
    widget: 'image'
    allowMultiple: false
    required: false
    hint: '500px by 120px. This image will be displayed on the list of guides.'
  - label: 'Search Terms'
    name: 'search-terms'
    widget: 'list'
    required: false
    hint: 'Comma separate a list of terms, nicknames, etc. that are relevant to this instance.'
  - label: 'Link to Video Guide'
    name: 'video-url'
    widget: 'string'
    required: false
  - *mechanic-fields
  - *boss-fields

collections:
  - name: 'ew'
    label: 'Endwalker'
    delete: false
    label_singular: 'Endwalker Guide'
    folder: 'src/guides/ew'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'shb'
    label: 'Shadowbringers'
    delete: false
    label_singular: 'Shadowbringers Guide'
    folder: 'src/guides/shb'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'sb'
    label: 'Stormblood'
    delete: false
    label_singular: 'Stormblood Guide'
    folder: 'src/guides/sb'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'hw'
    label: 'Heavensward'
    delete: false
    label_singular: 'Heavensward Guide'
    folder: 'src/guides/hw'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'arr'
    label: 'A Realm Reborn'
    delete: false
    label_singular: 'A Realm Reborn Guide'
    folder: 'src/guides/arr'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields
