backend:
  name: git-gateway
  repo: FFXIVPocketGuide/FFXIVPocketGuide
  branch: rebuild

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'static/assets/guides'

mechanic-fields: &mechanic-fields
  label: 'Instance-wide Mechanics'
  name: 'instance-mechanics'
  widget: 'list'
  fields:
    - label: 'Mechanic Name'
      name: 'name'
      widget: 'string'
    - label: 'Mechanic Steps'
      name: 'steps'
      widget: 'list'
      fields:
        - label: 'Step Name or Number'
          name: 'name'
          widget: 'string'
        - label: 'Step Notes'
          name: 'notes'
          widget: 'list'
          field:
            label: 'Step Note'
            name: ''
            widget: 'string'

attack-name: &attack-name
  label: 'Attack Name'
  name: 'name'
  widget: 'string'

attack-duty-action: &attack-duty-action
  label: 'Duty Action'
  name: 'duty-action'
  widget: 'list'
  field:
    label: 'Duty Action Name'
    name: ''
    widget: 'string'

attack-roles: &attack-roles
  label: 'Required Party Roles'
  name: 'roles'
  widget: 'select'
  multiple: true
  options:
    - 'Everyone'
    - 'Tank'
    - 'Healer'
    - 'Melee DPS'
    - 'Ranged DPS'

attack-tags: &attack-tags
  label: 'Attack Types'
  name: 'tags'
  widget: 'select'
  multiple: true
  options:
    - Active Time Maneuver
    - Animation
    - AoE (Area)
    - AoE (Cone)
    - AoE (Circle)
    - AoE (Column)
    - AoE (Cross)
    - AoE (Donut)
    - AoE (Figure 8)
    - AoE (Point-blank)
    - AoE (Proximity)
    - Buff
    - Cleave
    - Debuff
    - Divebomb
    - Gaze
    - Knockback
    - Line-of-sight
    - Marker (Blue)
    - Marker (Green)
    - Marker (Icon)
    - Marker (Orange)
    - Marker (Purple)
    - Marker (Red)
    - Marker (Yellow)
    - Minion
    - Pull
    - Puddle
    - Raid-wide Damage
    - Spread
    - Stack
    - Stun
    - Tankbuster
    - Tether
    - Ultimate
    - Unique Mechanic

attack-notes: &attack-notes
  label: 'Attack Notes'
  name: 'notes'
  widget: 'list'
  field:
    label: 'Details'
    name: ''
    widget: 'string'

attack-images: &attack-images
  label: 'Attack Images'
  name: 'images'
  widget: 'list'
  hint: 'Useful for highlighting particular choreography on the arena or specific iconographies or telegraphs.'
  fields:
    - label: 'Image Upload'
      name: 'image'
      widget: 'image'
    - label: 'Image Alt Text'
      name: 'alt'
      widget: 'string'
      hint: 'Used to describe the image to assistive technologies.'

boss-fields: &boss-fields
  label: 'Bosses'
  name: 'bosses'
  widget: 'list'
  fields:
    - label: 'Boss Name'
      name: 'name'
      widget: 'string'
      required: true
    - label: 'Fight Phases'
      name: 'phases'
      summary: 'Boss Phase'
      widget: 'list'
      fields:
        - label: 'Phase Notes'
          name: 'notes'
          widget: 'list'
          field:
            label: 'Phase Note'
            name: ''
            widget: 'string'
        - label: 'Attack Script'
          name: 'script'
          widget: 'list'
          hint: 'An optional list of attacks showing their order during the fight. This is particularly useful for choreographed fights.'
          fields:
            - label: 'Attack Name'
              name: 'attack'
              widget: 'string'
            - label: 'Is a duty action required for this attack?'
              name: 'duty-action'
              widget: 'boolean'
              required: false
        - label: 'Boss Attacks'
          name: 'attacks'
          widget: 'list'
          types:
            - label: 'Regular Attack'
              name: 'Regular'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - *attack-name
                - *attack-duty-action
                - *attack-roles
                - *attack-tags
                - *attack-notes
                - *attack-images
            - label: 'Combo Attack'
              name: 'Combo'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - label: 'Combo Name'
                  name: 'name'
                  widget: 'string'
                - label: 'Attacks in the Combo'
                  name: 'combos'
                  widget: 'list'
                  fields:
                    - *attack-name
                    - *attack-duty-action
                    - *attack-roles
                    - *attack-tags
                    - *attack-notes
                    - *attack-images
            - label: 'Attack with Variations'
              name: 'Variation'
              summary: '{{fields.name}}'
              widget: 'object'
              fields:
                - label: 'Attack Name'
                  name: 'name'
                  widget: 'string'
                - label: 'Variations of the Attack'
                  name: 'variations'
                  widget: 'list'
                  fields:
                    - *attack-name
                    - *attack-duty-action
                    - *attack-roles
                    - *attack-tags
                    - *attack-notes
                    - *attack-images

guide-fields: &guide-fields
  - label: 'Instance type'
    name: 'type'
    widget: 'select'
    options:
      - 'dungeon'
      - 'trial'
      - 'raid'
    required: true
  - label: 'Instance title'
    name: 'title'
    widget: 'string'
    required: true
  - label: 'Difficulty'
    name: 'difficulty'
    widget: 'select'
    options:
      - 'Normal'
      - 'Hard'
      - 'Extreme'
      - 'Savage'
      - 'Ultimate'
      - 'Unreal'
    required: true
  - label: 'Expansion'
    name: 'categories'
    widget: 'select'
    options:
      - label: 'Endwalker'
        value: 'endwalker'
      - label: 'Shadowbringers'
        value: 'shadowbringers'
      - label: 'Stormblood'
        value: 'stormblood'
      - label: 'Heavensward'
        value: 'heavensward'
      - label: 'A Realm Reborn'
        value: 'arealmreborn'
    required: true
  - label: 'Patch'
    name: 'patch'
    widget: 'number'
    value_type: 'string'
    hint: 'For expansion releases, please ensure to always include the decimal and 0. e.g. 5.0'
    required: true
  - label: 'Minimum player level'
    name: 'plvl'
    widget: 'number'
    value_type: 'string'
    required: true
  - label: 'Minimum item level'
    name: 'ilvl'
    widget: 'number'
    value_type: 'string'
    required: true
  - label: 'Guide order'
    name: 'order'
    widget: 'number'
    value_type: 'string'
    hint: 'This number determines where in the expansion the guide will fall on the homepage. Please combine the player level and item level together for best results. (e.g. 80 + 255 = 80255 )'
  - label: 'Image'
    name: 'img'
    widget: 'image'
    hint: "1500px by 300px. This image will be displayed in the guide's header background."
    allowMultiple: false
    required: true
  - label: 'Search terms'
    name: 'search-terms'
    widget: 'list'
    required: false
    hint: "Comma separate a list of terms, nicknames, etc. that are relevant to this instance. Note that the name, expansion, difficulty, and boss names are all added automatically by the system, so there's no need to include them here."
  - label: 'Video guide'
    name: 'video'
    widget: 'string'
    required: false
    hint: 'Generally speaking this is a link to the relevant MTQCapture video guide.'
  - *mechanic-fields
  - *boss-fields

collections:
  - name: 'dawntrail'
    label: 'Dawntrail'
    delete: false
    extension: json
    label_singular: 'Dawntrail Guide'
    folder: 'src/_data/guides/7-dawntrail'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'endwalker'
    label: 'Endwalker'
    delete: false
    extension: json
    label_singular: 'Endwalker Guide'
    folder: 'src/_data/guides/6-endwalker'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'shadowbringers'
    label: 'Shadowbringers'
    delete: false
    extension: json
    label_singular: 'Shadowbringers Guide'
    folder: 'src/_data/guides/5-shadowbringers'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'stormblood'
    label: 'Stormblood'
    delete: false
    extension: json
    label_singular: 'Stormblood Guide'
    folder: 'src/_data/guides/4-stormblood'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'heavensward'
    label: 'Heavensward'
    delete: false
    extension: json
    label_singular: 'Heavensward Guide'
    folder: 'src/_data/guides/3-heavensward'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields

  - name: 'a-realm-reborn'
    label: 'A Realm Reborn'
    delete: false
    extension: json
    label_singular: 'A Realm Reborn Guide'
    folder: 'src/_data/guides/2-a-realm-reborn'
    create: true
    editor:
      preview: true
    slug: '{{year}}-{{month}}-{{day}}-{{patch}}-{{fields.slug}}'
    summary: '{{title}} ({{difficulty}}) -- {{year}}/{{month}}/{{day}}'
    filter: { field: 'cms', value: 'netlify-cms' }
    fields: *guide-fields
