# local_backend: true

backend:
  name: git-gateway
  repo: FFXIVPocketGuide/FFXIVPocketGuide
  branch: rebuild

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'static/assets/guides'

mechanic-fields: &mechanic-fields
  label: 'Instance-wide mechanics'
  label_singular: 'mechanic'
  name: 'mechanics'
  widget: 'list'
  fields:
    - label: 'Name'
      name: 'name'
      widget: 'string'
    - label: 'Steps'
      label_singular: 'step'
      name: 'steps'
      widget: 'list'
      fields:
        - label: 'Step name or number'
          name: 'name'
          widget: 'string'
        - label: 'Notes'
          label_singular: 'note'
          name: 'notes'
          widget: 'list'
          field:
            label: 'Note'
            name: 'note'
            widget: 'string'

attack-name: &attack-name
  label: 'Attack name'
  name: 'name'
  widget: 'string'

attack-duty-action: &attack-duty-action
  label: 'Duty action'
  name: 'action'
  widget: 'list'
  field:
    label: 'Action name'
    name: 'name'
    widget: 'string'

attack-roles: &attack-roles
  label: 'Party roles'
  name: 'roles'
  widget: 'select'
  multiple: true
  options:
    - 'Everyone'
    - 'Tank'
    - 'Healer'
    - 'Melee DPS'
    - 'Ranged DPS'

attack-tags: &attack-tags
  label: 'Type of attack'
  name: 'tags'
  widget: 'select'
  multiple: true
  options:
    - Active time maneuver
    - Animation
    - AoE (Area)
    - AoE (Cone)
    - AoE (Circle)
    - AoE (Column)
    - AoE (Cross)
    - AoE (Donut)
    - AoE (Figure 8)
    - AoE (Point-blank)
    - AoE (Proximity)
    - Buff
    - Cleave
    - Debuff
    - Divebomb
    - Gaze
    - Knockback
    - Line-of-sight
    - Marker (Blue)
    - Marker (Green)
    - Marker (Icon)
    - Marker (Orange)
    - Marker (Purple)
    - Marker (Red)
    - Marker (Yellow)
    - Minion
    - Pull
    - Puddle
    - Raid-wide damage
    - Spread
    - Stack
    - Stun
    - Tankbuster
    - Tether
    - Ultimate
    - Unique mechanic

attack-notes: &attack-notes
  label: 'Notes'
  label_singular: 'note'
  name: 'notes'
  widget: 'list'
  field:
    label: 'Note'
    name: 'note'
    widget: 'string'

attack-images: &attack-images
  label: 'Attack images'
  label_singular: 'image'
  name: 'images'
  widget: 'list'
  hint: 'Useful for highlighting particular choreography on the arena or specific iconographies or telegraphs.'
  fields:
    - label: 'Image upload'
      name: 'image'
      widget: 'image'
    - label: 'Image alt text'
      name: 'alt'
      widget: 'string'
      hint: 'Used to describe the image to assistive technologies.'

attack: &attack
  label: 'Boss attacks'
  label_singular: 'attack'
  name: 'attacks'
  widget: 'list'
  types:
    - label: 'Regular attack'
      label_singular: 'attack'
      name: 'regular'
      summary: '{{fields.name}}'
      widget: 'object'
      fields:
        - *attack-name
        - *attack-duty-action
        - *attack-roles
        - *attack-tags
        - *attack-notes
        - *attack-images
    - label: 'Attack with variations'
      name: 'variation'
      summary: '{{fields.name}}'
      widget: 'object'
      fields:
        - label: 'General name'
          name: 'name'
          widget: 'string'
        - label: 'Variations of the attack'
          label_singular: 'attack'
          name: 'variations'
          widget: 'list'
          fields:
            - *attack-name
            - *attack-duty-action
            - *attack-roles
            - *attack-tags
            - *attack-notes
            - *attack-images

boss-fields: &boss-fields
  label: 'Bosses'
  label_singular: 'boss'
  name: 'bosses'
  widget: 'list'
  fields:
    - label: 'Boss Name'
      name: 'name'
      widget: 'string'
      required: true
    - *attack
    - label: 'Fight Phases'
      label_singular: 'phase'
      name: 'phases'
      widget: 'list'
      fields:
        - label: 'Notes'
          label_singular: 'note'
          name: 'notes'
          widget: 'list'
          hint: 'These notes should be used to describe general events or things to keep an eye out for during this particular phase.'
          field:
            label: 'Note'
            name: 'note'
            widget: 'string'
        - label: 'Attack sequence'
          label_singular: 'attack group'
          name: 'sequence'
          widget: 'list'
          hint: 'An optional list of attacks showing their order during the fight. This is particularly useful for choreographed fights. Attack groups can be used to collect a series of attacks to indicate repeated cycles. Because most attacks happen in isolation, it will be common to only have a single attack in any given group.'
          fields:
            - label: 'Group type'
              name: 'type'
              widget: 'select'
              options:
                - { label: 'Single attack', value: 'single' }
                - { label: 'Linear combo', value: 'combo' }
                - { label: 'Possible options', value: 'possible' }
              hint: 'Use "Single attack" if there is only 1 attack in the group. Use "Linear combo" when there are a series of attacks that happen in quick succession. Use "Possible options" when the boss will perform 1 of many possible attacks.'
            - label: 'Does this group repeat?'
              name: 'repeat'
              widget: 'boolean'
              required: false
            - label: 'Attacks'
              label_singular: 'attack'
              name: 'attacks'
              widget: 'list'
              field: { label: 'Attack', name: 'attack', widget: 'string' }

guide-fields: &guide-fields
  - label: 'Instance type'
    name: 'type'
    widget: 'select'
    options:
      - 'dungeon'
      - 'trial'
      - 'raid'
    required: true
  - label: 'Instance title'
    name: 'title'
    widget: 'string'
    required: true
  - label: 'Difficulty'
    name: 'difficulty'
    widget: 'select'
    options:
      - 'normal'
      - 'hard'
      - 'extreme'
      - 'savage'
      - 'ultimate'
      - 'unreal'
    required: true
  - label: 'Patch'
    name: 'patch'
    widget: 'object'
    fields:
      - label: 'Patch number'
        name: 'number'
        widget: 'string'
        value_type: 'string'
        hint: 'For expansion releases, please ensure to always include the decimal and 0. e.g. 5.0'
      - label: 'Patch name'
        name: 'name'
        widget: 'string'
        value_type: 'string'
    required: true
  - label: 'Minimum player level'
    name: 'plvl'
    widget: 'string'
    value_type: 'string'
    required: true
    hint: 'This number should always be 3 digits. Prefix double or single digit numbers with 0s. (e.g. 034)'
  - label: 'Minimum item level'
    name: 'ilvl'
    widget: 'string'
    value_type: 'string'
    required: true
    hint: 'This number should always be 3 digits. Prefix double or single digit numbers with 0s. (e.g. 034)'
  - label: 'Guide order'
    name: 'order'
    widget: 'string'
    value_type: 'string'
    hint: 'This number determines where in the expansion the guide will fall on the homepage and should always be 6 digits. Please combine the player level and item level together for best results. (e.g. 080 + 255 = 80255)'
  - label: 'Image'
    name: 'img'
    widget: 'image'
    hint: "1500px by 300px. This image will be displayed in the guide's header background."
    allowMultiple: false
    required: true
  - label: 'Search terms'
    name: 'terms'
    widget: 'list'
    required: false
    hint: "Comma separate a list of terms, nicknames, etc. that are relevant to this instance. Note that the name, expansion, difficulty, and boss names are all added automatically by the system, so there's no need to include them here."
  - label: 'Orchestrion roll'
    name: 'orchestrion'
    widget: 'string'
    value_type: 'string'
    required: false
  - label: 'Video guide'
    name: 'video'
    widget: 'string'
    required: false
    hint: 'Generally speaking this is a link to the relevant MTQCapture video guide.'
  - *mechanic-fields
  - *boss-fields

collections:
  - name: 'dawntrail'
    label: 'Dawntrail'
    delete: false
    extension: json
    label_singular: 'Dawntrail Guide'
    folder: 'src/_data/guides/7-dawntrail'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields

  - name: 'endwalker'
    label: 'Endwalker'
    delete: false
    extension: json
    label_singular: 'Endwalker Guide'
    folder: 'src/_data/guides/6-endwalker'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields

  - name: 'shadowbringers'
    label: 'Shadowbringers'
    delete: false
    extension: json
    label_singular: 'Shadowbringers Guide'
    folder: 'src/_data/guides/5-shadowbringers'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields

  - name: 'stormblood'
    label: 'Stormblood'
    delete: false
    extension: json
    label_singular: 'Stormblood Guide'
    folder: 'src/_data/guides/4-stormblood'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields

  - name: 'heavensward'
    label: 'Heavensward'
    delete: false
    extension: json
    label_singular: 'Heavensward Guide'
    folder: 'src/_data/guides/3-heavensward'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields

  - name: 'a-realm-reborn'
    label: 'A Realm Reborn'
    delete: false
    extension: json
    label_singular: 'A Realm Reborn Guide'
    folder: 'src/_data/guides/2-a-realm-reborn'
    create: true
    editor:
      preview: false
    slug: '{{slug}}-{{title}}'
    summary: '{{title}} ({{difficulty}})'
    fields: *guide-fields
